### PR TITLE
Update egui to 0.19

### PR DESCRIPTION
**Pull request by inact1v1ty**
Update:

- `egui` `0.18` -> `0.19`
- `glam` `0.20` -> `0.21.2`
- `wgpu` `0.12` -> `0.13`
- `winit` `0.26` -> `0.27.2`
- `rend3` `1b6cac4` -> `dbdfc32`
- `egui_node_graph` `54ae2dc` -> `75308d0`

And update the code to account for API changes.

No more need for custom `egui_wgpu`/`egui_winit` fork!

The only issue I see now is that at high levels of zoom there are warnings at console stating:
`epaint: WARNING: pixels_per_point (dpi scale) have changed between text layout and tessellation. You must recreate your text shapes if pixels_per_point changes.`

Seems that this check appeared in `epaint` between 0.18 and 0.19, so that `blackjack` with egui-0.18 just didn't show it, as the line that produces this warning is [this one](https://github.com/inact1v1ty/blackjack/blob/6430a782aff2cdc78e812630e860c3b308271fae/blackjack_ui/src/application/graph_editor.rs#L149). I didn't touch it, but if I remove it the warning disappears (but everything gets somewhat blurry on zoom 0.5 and too crisp on zoom > 1).

### CODE REVIEW

**Comment by setzer22** [comment]
Oh, and feel free to silence that clippy warning, no need to address it. Clippy can be a bit too opinionated sometimes :+1:

**Comment by inact1v1ty** [comment]
I am very glad that this is so helpful for you! 🎉 

> One thing I don't get is that I clearly remember having introduced a few changes to egui_wgpu that had to do specifically with zooming 🤔 I'd been porting these changes from a while ago, but maybe they stopped being necessary at some point? Zooming seems to work just fine now.

Yeah, "it just works". I cloned `egui_wgpu` locally and messed with it until it appeared the with slight modifications to the values passed I can go without modifying the `egui_wgpu` itself.

As for the `egui_winit`, I was able to work around it based on underlying logic and left a [comment](https://github.com/inact1v1ty/blackjack/blob/50047484a8d82e9f1f1c13b2cad19dcdc4cb3149/blackjack_ui/src/application/graph_editor.rs#L151) describing the solution.

> Another potential solution, looking at the warning text, is making this dpi adjustment somewhere else, so that the change is no longer happening between layout (essentially, all the UI code) and tessellation (right before rendering).

I'll try to do so, and if not successful, just go with "it's okay" and make zoom a bit higher I think.

**Comment by inact1v1ty** [comment]
Well, I tried to make it not complain about changing `pixels_per_point`, but didn't succeed. And for the second option: even with `ZOOM_LEVEL_MAX` set to `4.0` it appears randomly, and setting it to a lesser value seems not right for usability.

So, it seems that at the time being we just live with it and wait for [this](https://github.com/emilk/egui/issues/1811) 🙁

**Review by setzer22 — APPROVED** [review]
Alright, just went over the changes. Everything looks good, thanks so much! :smile:

**Comment by setzer22** [comment]
> So, it seems that at the time being we just live with it and wait for [this](https://github.com/emilk/egui/issues/1811) slightly_frowning_face

Yup, I'm not happy about the warning spam on the console either, but as long as things work I wouldn't spend any more time trying to debug this. At least not at this time :+1:

**Pull request merged**
