### PR TITLE
Add `MPL-2.0` SPDX identifier and missing Cargo metadata

### PR DESCRIPTION
**Pull request by Bromeon**
Changes:
* replaces some occurrences of `"MIT"` with `"MPL-2.0"` (see [SPDX identifier](https://spdx.org/licenses/MPL-2.0.html))
* adds missing metadata to each crate
* uses same order for fields everywhere

### CODE REVIEW

**Comment by setzer22** [comment]
Thanks a lot! :smile:

**Comment by Bromeon** [comment]
Another question, do you have an official MSRV (minimal supported Rust version)?
[If yes, this can also be specified in `Cargo.toml`:](https://doc.rust-lang.org/cargo/reference/manifest.html#the-rust-version-field)
```toml
[package]
rust-version = "1.56"
```

**Comment by setzer22** [comment]
I don't, but I probably should. I've been bit in the past by having used some features that were just stabilized and then builds would start breaking in older compiler versions (sometimes with not-so-nice error messages).

Any suggestions for what a good MSRV would be? I know you picked one for godot-rust based on community usage, so if blackjack builds under that, it might be a good choice as well :smile:

**Comment by Bromeon** [comment]
> Any suggestions for what a good MSRV would be? I know you picked one for godot-rust based on community usage, so if blackjack builds under that, it might be a good choice as well 😄

I would choose the minimum one that builds with the current codebase, and then stick with it until there are reasons to upgrade. In case you publish to crates.io in the future, you'd need to keep in mind that increasing MSRV is a breaking change, so you might rather want to start with a newer version to extend the period of time without needing to bump it.

Now, how to find the MSRV? [Look at this](https://github.com/Bromeon/blackjack/actions/runs/3369658759/jobs/5589582771) 😀

If you wonder about `1.6` and `1.5`, that's the beauty of YAML interpreting `1.50` as a number 🤦‍♂️
Anyway, that didn't matter. Since there were two releases for `1.62` and this was exactly the boundary, I [increased the resolution](https://github.com/Bromeon/blackjack/actions/runs/3369895623). 🔬

**Comment by setzer22** [comment]
Thanks for the amazing work! It didn't occur to me you could (ab)use github actions like that :grin:. `1.62` it is then! Do you mind pushing that on your end, since it's your branch I don't want to overwrite it with new commits.

> If you wonder about 1.6 and 1.5, that's the beauty of YAML interpreting 1.50 as a number man_facepalming
Ah, the wonders of YAML :rofl: 

> Looks like in this case, the limiting factor are your dependencies, more concretely, inventory.
Ah, makes sense, inventory has only recently started working again after the rustc bug got fixed :+1:

**Review by setzer22 — APPROVED** [review]

**Comment by Bromeon** [comment]
Added another commit with the MSRV 1.62. I also mentioned it in the ReadMe, let me know if you want me to reword it.

Another little trick: by reformatting the `Note` in Markdown, you can make use of GitHub's rich formatting. I used the freedom to apply this 😉 
note

**Comment by setzer22** [comment]
Great stuff! This looks ready to merge 👍

**Pull request merged**
